### PR TITLE
Fixed clear screen issue.

### PR DESCRIPTION
**Pull request by surajkadapa**
The clear screen issue has been cleared, by adding the clear command which can be used for unix systems.

### CODE REVIEW

**Comment by suhaskv1** [comment]
!bounty 30

**Comment by suhaskv1** [comment]
!bounty 30

**Comment by suhaskv1** [comment]
!bounty 30

**Comment by suhaskv1** [comment]
@surajkadapa bounty points allotted! Good job! :)

**Comment by surajkadapa** [comment]
Thanksss @suhaskv1

**Pull request merged**
