### PR TITLE
FINAL Added Up/Down Speed using subprocess, Fixed UI, Fixed latency formatting

### PR DESCRIPTION
**Pull request by ramselvaraj**
#30  Added Network Down and Up speed, using subprocess and VNstat (linux only)
#31  Cleaned up the UI
#29  Fixed Latency Form

###  REQUIREMENTS-
VNstat for Linux

**Final Out-** Watching YT video with speed tracking, and pre existing netstat function showing google.com pings in a formatted manner
finalRP

Just NetSpeed function() with resource monitoring, UI improvement-
up Down Speed

Custom NetSpeed Function()-
netDisplayFunc

Print Statement to print to cmd-
printing

Formtting done using string slicing, viewable in code

@suhaskv1

### CODE REVIEW

**Comment by suhaskv1** [comment]
@ramselvaraj code does not run on Linux systems. Please mitigate this issue as the tool must run on all the major OSs. If you can fix the issue, I will allot the bounty points.

**Comment by suhaskv1** [comment]
@ramselvaraj looks good but please fix some formatting with respect to packets received and sent. Also please have exception handling for when ping cannot be achieved (i.e. system is offline). If you can send in a commit on these changes, I will allot the points. Also add "vnstat" in requirements or update the readme to direct the user or dev to install it.

**Comment by ramselvaraj** [comment]
> @ramselvaraj looks good but please fix some formatting with respect to packets received and sent. Also please have exception handling for when ping cannot be achieved (i.e. system is offline). If you can send in a commit on these changes, I will allot the points. Also add "vnstat" in requirements or update the readme to direct the user or dev to install it.

okay, i will add the req and do the error handling

**Comment by suhaskv1** [comment]
The up and down speeds seem not be updating. You can try to async all the dynamic data because it seems to be holding old data and updating it repeated due to off time_delay between CPU and Memory info and the network info. I suggest you create two different delays for each of these

**Comment by ramselvaraj** [comment]
> The up and down speeds seem not be updating. You can try to async all the dynamic data because it seems to be holding old data and updating it repeated due to off time_delay between CPU and Memory info and the network info. I suggest you create two different delays for each of these

from my testing it was updating, but maybe not at the same speed as cpu and mem speed, what if i set the time delay to the same as the speed tests time delay?

**Comment by ramselvaraj** [comment]
what error handling do you want @suhaskv1 ? Only show the other non network stats or kill the program?

**Pull request closed without merging**
